include(CMakeParseArguments)

function(zh_require_program output name package_help)
  if(ZH_DEPENDENCY_PROBE_EMPTY)
    find_program(found_program NAMES "${name}" PATHS "${CMAKE_CURRENT_LIST_DIR}/intentionally-empty" NO_DEFAULT_PATH)
  else()
    find_program(found_program NAMES "${name}")
  endif()
  if(NOT found_program)
    message(FATAL_ERROR "Missing required program '${name}'. Install ${package_help}.")
  endif()
  set(${output} "${found_program}" PARENT_SCOPE)
endfunction()

function(zh_find_distribution_dependencies)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(SDL3 REQUIRED IMPORTED_TARGET sdl3>=3.2)
  add_library(SDL3::SDL3 ALIAS PkgConfig::SDL3)

  find_package(Freetype 2 REQUIRED)
  find_package(Fontconfig REQUIRED)
  find_package(ZLIB REQUIRED)

  foreach(component IN ITEMS avformat avcodec avutil swscale swresample)
    string(TOUPPER "${component}" component_upper)
    pkg_check_modules(${component_upper} REQUIRED IMPORTED_TARGET "lib${component}")
    add_library(FFmpeg::${component} ALIAS PkgConfig::${component_upper})
  endforeach()

  zh_require_program(ZH_GLSLC_EXECUTABLE glslc "the shaderc/glslc distribution package")
  set(ZH_GLSLC_EXECUTABLE "${ZH_GLSLC_EXECUTABLE}" PARENT_SCOPE)

  message(STATUS "Dependency SDL3: ${SDL3_VERSION}")
  message(STATUS "Dependency FreeType: ${FREETYPE_VERSION_STRING}")
  message(STATUS "Dependency Fontconfig: ${Fontconfig_VERSION}")
  message(STATUS "Dependency zlib: ${ZLIB_VERSION}")
  message(STATUS "Dependency FFmpeg libavformat: ${AVFORMAT_VERSION}")
  message(STATUS "Dependency glslc: ${ZH_GLSLC_EXECUTABLE}")
endfunction()
